In [169]:
import pandas as pd
import numpy as np

In [170]:
file1 =("pandashomeworkfolder/purchase_data.csv")

In [171]:
purchasedata = pd.read_csv(file1)
purchasedata.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44

In [172]:
#collect all players
players = len(purchasedata)
numberofplayers = pd.DataFrame([players], columns = ["Total Players"])
#numberofplayers = pd.df([players]) = ["Total Players"]
numberofplayers

   Total Players
0            780

In [173]:
averagepurchaseprice = purchasedata["Price"].mean()
averagepurchaseprice

averageprice1 = np.round(averagepurchaseprice,2)
averageprice1

3.05

In [174]:
numberofpurchases = purchasedata["Price"].mean()
numberofpurchases

3.0509871794871795

In [175]:
#uniqueitems = numberofpurchases
uniqueitems = purchasedata["Item ID"].nunique()
uniqueitems

179

In [176]:
totalrevenue = purchasedata["Price"].sum()
totalrevenue

2379.77

In [177]:
purchasetable = pd.DataFrame({"Number Of Unique Items": [uniqueitems],
                             "Average Price": [averagepurchaseprice],
                             "Number Of Purchases": [numberofpurchases],
                             "Total Revenue": [totalrevenue]})
purchasetable.style.format({"Average Price":"${:.2f}", "Total Revenue":"${:.2f}"})

In [178]:
genderdemo = purchasedata.groupby(["Gender"])

In [179]:
purchasecount = genderdemo ["Gender"].count()

In [180]:
totalcount = genderdemo ["Gender"].count()
totalcount1 = [purchasecount[0], purchasecount[1], purchasecount[2]]

In [181]:
#begin gender
genderpercentage = [round((purchasecount[0]/numberofplayers)*100,2),round((purchasecount[1]/numberofplayers)*100,2),round((purchasecount[2]/numberofplayers)*100,2)]

In [182]:
genderdemo = pd.DataFrame({"Percentage Of Players": genderpercentage, "Total Count": totalcount1})
genderdemo.index = (["Male Players", "Female Players", "Other/Non Disclosed"])
genderdemo

                                 Percentage Of Players  Total Count
Male Players            Total Players
0          14.49          113
Female Players          Total Players
0          83.59          652
Other/Non Disclosed     Total Players
0           1.92           15

In [183]:
genderdemo = purchasedata.groupby(["Gender"])

In [184]:
#nextgender
purchasecount = genderdemo["SN"].count()

In [185]:
purchaseprice = genderdemo["Price"].mean()

In [186]:
purchasevalue = genderdemo["Price"].sum()

In [187]:
duplicates = purchasedata.drop_duplicates(subset = "SN", keep = "first")
duplicates1 = duplicates.groupby(["Gender"])

In [188]:
purchasebygender = (genderdemo["Price"].sum()/duplicates1["SN"].count())

In [189]:
genderanalysis = pd.DataFrame({"Purchase Count": purchasecount,
                              "Average Purchase Price": purchaseprice,
                               "Total Purchase Value": purchasevalue,
                               "Avg Purchase By Gender": purchasebygender})

In [190]:
#genderanalysis["Purchase Count"] = genderanalysis["Purchase Count"].map()
genderanalysis["Average Purchase Price"] = genderanalysis["Average Purchase Price"].map("${:.2f}".format)
genderanalysis["Total Purchase Value"] = genderanalysis["Total Purchase Value"].map("${:.2f}".format)
genderanalysis["Avg Purchase By Gender"] = genderanalysis["Avg Purchase By Gender"].map("${:.2f}".format)
genderanalysis = genderanalysis[["Purchase Count", "Average Purchase Price", "Total Purchase Value", "Avg Purchase By Gender"]]
genderanalysis

,Purchase Count,Average Purchase Price,Total Purchase Value,Avg Purchase By Gender
Gender,,,,
Female,113,$3.20,$361.94,$4.47
Male,652,$3.02,$1967.64,$4.07
Other / Non-Disclosed,15,$3.35,$50.19,$4.56

In [191]:
bins = [0, 9, 14, 19, 24, 29, 34, 39, 100]
bincategories = ["<10", "10-14", "15-19", "20-24","25-29","30-34","35-39","40+"]

In [192]:
#pd.cut(purchasedata["Age"], bins, labels = bincategories)
#purchasedata["Age Group"] = pd.cut(purchasedata["Age"], bins, labels = bincategories)
#groupbyage = purchasedata.groupby(["SN", "Age", "Gender"])
#agegroup = pd.DataFrame(groupbyage())

In [193]:
#agegroupdf = pd.DataFrame(agegroup.groupby(["Age Group"]).count())
#agegroupdf.columns = ["Purchase Count"]

In [202]:
#purchasedata["Purchase Count"]=pd.cut(purchasedata["Price"], bins, labels=bincategories, include_lowest=True)
#pd.cut(purchasedata["Price"].mean(), bins, labels=bincategories, include_lowest=True)
#pd.cut(purchasedata["Price"], bins, labels=bincategories, include_lowest=True)
#pd.cut(purchasedata["Price"], bins, labels=bincategories, include_lowest=True)

In [203]:
#purchasedata["Avg Purchase Price"]=pd.cut(purchasedata["Price"].mean(), bins)

In [206]:
pd.cut(purchasedata["Age"], bins, labels=bincategories)

0      20-24
1        40+
2      20-24
3      20-24
4      20-24
       ...
775    20-24
776    20-24
777    20-24
778      <10
779    20-24
Name: Age, Length: 780, dtype: category
Categories (8, object): ['<10' < '10-14' < '15-19' < '20-24' < '25-29' < '30-34' < '35-39' < '40+']

In [214]:
purchasedata["Age Categories"] = pd.cut(purchasedata["Age"], bins, labels=bincategories)
#pd.cut(purchasedata["Price"], bins, labels=bincategories.mean())

In [227]:
agegroup1 = purchasedata.groupby(["Age Categories"])

In [228]:
agegroup2 = purchasedata.count()["Purchase ID"]

In [229]:
#agegroup3 = purchasedata.groupby(["Price"])

In [230]:
agegroup3 = purchasedata.mean()["Price"]

In [231]:
agegroup4 = purchasedata.sum()["Price"]

In [232]:
agegroup5 = purchasedata.sum()["Price"]/agegroup1["SN"].nunique()

In [238]:
#agedemographics = pd.DataFrame({"Purchase Count": agegroup1,
                               #"Avg Purchase Price": agegroup2,
                              # "Total Purchase Value": agegroup3,
                              # "Avg Purchase/person/gender": agegroup4
                              # })
#agedemographics

In [239]:
agedemographics = pd.DataFrame({"Purchase Count": agegroup2,
                              "Avg Purchase Price": agegroup3,
                               "Total Purchase Value": agegroup4,
                               "Avg Purchase/person/gender": agegroup5
                               })
agedemographics

,Purchase Count,Avg Purchase Price,Total Purchase Value,Avg Purchase/person/gender
Age Categories,,,,
<10,780,3.050987,2379.77,139.986471
10-14,780,3.050987,2379.77,108.171364
15-19,780,3.050987,2379.77,22.240841
20-24,780,3.050987,2379.77,9.223915
25-29,780,3.050987,2379.77,30.906104
30-34,780,3.050987,2379.77,45.764808
35-39,780,3.050987,2379.77,76.766774
40+,780,3.050987,2379.77,198.314167

In [240]:
#just like previous tasks - strat with new name; function; what we want to pull
topspenders1 = purchasedata.groupby(["SN"])
#topspenders2 = purchasedata.groupby([])
topspenders2 = purchasedata.count()["Price"]
topspenders3 = purchasedata.mean()["Price"]
topspenders4 = purchasedata.sum()["Price"]

In [241]:
topspendersdf = pd.DataFrame({"SN": topspenders1,
                             "Purchase Count": topspenders2,
                             "Avg Purchase Price": topspenders3,
                             "Total Purchase Value": topspenders4})

ValueError: If using all scalar values, you must pass an index