In [77]:
import pandas as pd
import numpy as np

In [78]:
file1 =("pandashomeworkfolder/purchase_data.csv")

In [79]:
purchasedata = pd.read_csv(file1)

In [80]:
#player count
players = len(purchasedata)
numberofplayers = pd.DataFrame([players], columns = ["Total Players"])
#numberofplayers = pd.df([players]) = ["Total Players"]
numberofplayers

   Total Players
0            780

In [81]:
#purchase analysis
averagepurchaseprice = purchasedata["Price"].mean()
averagepurchaseprice

averageprice1 = np.round(averagepurchaseprice,2)
averageprice1

3.05

In [82]:
numberofpurchases = purchasedata["Price"].count()
numberofpurchases

780

In [83]:
#uniqueitems = numberofpurchases
uniqueitems = purchasedata["Item ID"].nunique()
uniqueitems

179

In [84]:
totalrevenue = purchasedata["Price"].sum()
totalrevenue

2379.77

In [85]:
purchasetable = pd.DataFrame({"Number Of Unique Items": [uniqueitems],
                             "Average Price": [averagepurchaseprice],
                             "Number Of Purchases": [numberofpurchases],
                             "Total Revenue": [totalrevenue]})
purchasetable.style.format({"Average Price":"${:.2f}", "Total Revenue":"${:.2f}"})

In [86]:
#begin gender
genderdemo = purchasedata.groupby(["Gender"])

In [87]:
purchasecount = genderdemo ["Gender"].count()

In [88]:
totalcount = genderdemo ["Gender"].count()
totalcount1 = [purchasecount[0], purchasecount[1], purchasecount[2]]

In [89]:
genderpercentage = [round((purchasecount[0]/numberofplayers)*100,2),round((purchasecount[1]/numberofplayers)*100,2),round((purchasecount[2]/numberofplayers)*100,2)]

In [90]:
genderdemo = pd.DataFrame({"Percentage Of Players": genderpercentage, "Total Count": totalcount1})
genderdemo.index = (["Female Players", "Male Players", "Other/Non Disclosed"])
genderdemo

                                 Percentage Of Players  Total Count
Female Players          Total Players
0          14.49          113
Male Players            Total Players
0          83.59          652
Other/Non Disclosed     Total Players
0           1.92           15

In [91]:
genderdemo = purchasedata.groupby(["Gender"])

In [92]:
#nextgender - purchasing analysis
purchasecount = genderdemo["SN"].count()

In [93]:
purchaseprice = genderdemo["Price"].mean()

In [94]:
purchasevalue = genderdemo["Price"].sum()

In [95]:
duplicates = purchasedata.drop_duplicates(subset = "SN", keep = "first")
duplicates1 = duplicates.groupby(["Gender"])

In [96]:
purchasebygender = (genderdemo["Price"].sum()/duplicates1["SN"].count())

In [97]:
genderanalysis = pd.DataFrame({"Purchase Count": purchasecount,
                              "Average Purchase Price": purchaseprice,
                               "Total Purchase Value": purchasevalue,
                               "Avg Purchase By Gender": purchasebygender})

In [98]:
#genderanalysis["Purchase Count"] = genderanalysis["Purchase Count"].map()
genderanalysis["Average Purchase Price"] = genderanalysis["Average Purchase Price"].map("${:.2f}".format)
genderanalysis["Total Purchase Value"] = genderanalysis["Total Purchase Value"].map("${:.2f}".format)
genderanalysis["Avg Purchase By Gender"] = genderanalysis["Avg Purchase By Gender"].map("${:.2f}".format)
genderanalysis = genderanalysis[["Purchase Count", "Average Purchase Price", "Total Purchase Value", "Avg Purchase By Gender"]]
genderanalysis

,Purchase Count,Average Purchase Price,Total Purchase Value,Avg Purchase By Gender
Gender,,,,
Female,113,$3.20,$361.94,$4.47
Male,652,$3.02,$1967.64,$4.07
Other / Non-Disclosed,15,$3.35,$50.19,$4.56

In [99]:
#age demo
bins = [0, 9, 14, 19, 24, 29, 34, 39, 100]
bincategories = ["<10", "10-14", "15-19", "20-24","25-29","30-34","35-39","40+"]

In [103]:
#purchasedata["Avg Purchase Price"]=pd.cut(purchasedata["Price"].mean(), bins)

In [104]:
pd.cut(purchasedata["Age"], bins, labels=bincategories)

0      20-24
1        40+
2      20-24
3      20-24
4      20-24
       ...
775    20-24
776    20-24
777    20-24
778      <10
779    20-24
Name: Age, Length: 780, dtype: category
Categories (8, object): ['<10' < '10-14' < '15-19' < '20-24' < '25-29' < '30-34' < '35-39' < '40+']

In [105]:
purchasedata["Age Categories"] = pd.cut(purchasedata["Age"], bins, labels=bincategories)
#pd.cut(purchasedata["Price"], bins, labels=bincategories.mean())

In [106]:
agegroup1 = purchasedata.groupby(["Age Categories"])

In [107]:
agegroup2 = purchasedata.count()["Purchase ID"]

In [115]:
#agegroup3 = purchasedata.groupby(["Price"])

In [116]:
agegroup3 = purchasedata.mean()["Price"]

In [117]:
agegroup4 = purchasedata.sum()["Price"]

In [118]:
agegroup5 = purchasedata.sum()["Price"]/agegroup1["SN"].nunique()

In [119]:
#agedemographics = pd.DataFrame({"Purchase Count": agegroup1,
                               #"Avg Purchase Price": agegroup2,
                              # "Total Purchase Value": agegroup3,
                              # "Avg Purchase/person/gender": agegroup4
                              # })
#agedemographics

In [127]:
agedemographics = pd.DataFrame({"Purchase Count": agegroup2,
                              "Avg Purchase Price": agegroup3,
                               "Total Purchase Value": agegroup4,
                               "Avg Purchase Total by Age": agegroup5
                               })
agedemographics

,Purchase Count,Avg Purchase Price,Total Purchase Value,Avg Purchase Total by Age
Age Categories,,,,
<10,780,3.050987,2379.77,139.986471
10-14,780,3.050987,2379.77,108.171364
15-19,780,3.050987,2379.77,22.240841
20-24,780,3.050987,2379.77,9.223915
25-29,780,3.050987,2379.77,30.906104
30-34,780,3.050987,2379.77,45.764808
35-39,780,3.050987,2379.77,76.766774
40+,780,3.050987,2379.77,198.314167

In [130]:
#top spenders
topspenders1 = purchasedata.groupby(["SN"])
#topspenders2 = purchasedata.groupby([])
topspenders2 = purchasedata.count()["Price"]
topspenders3 = purchasedata.mean()["Price"]
topspenders4 = purchasedata.sum()["Price"]
topspenders5 = purchasedata.sum()["Price"]/agegroup1["Age"].nunique()

In [131]:
topspendersdf = pd.DataFrame({"Purchase Count": [topspenders2],
                             "Avg Purchase Price": [topspenders3],
                             "Total Purchase Value": [topspenders4],
                             "Avg Purchase Total by Age Group": [topspenders5]})
                             
topspendersdf

,Purchase Count,Avg Purchase Price,Total Purchase Value,Avg Purchase Total by Age Group
0,780,3.050987,2379.77,Age Categories <10 793.256667 10-14 47...

In [123]:
#most popular items
mostpopular1 = purchasedata.groupby(["SN"])
mostpopular2 = purchasedata.count()["Item ID"]
mostpopular3 = purchasedata.count()["Item Name"]
mostpopular4 = purchasedata.count()["Price"]
mostpopular5 = purchasedata.sum()["Price"]
mostpopular6 = purchasedata.sum()["Price"]

#mostpopulardf = pd.DataFrame({})

In [124]:
mostpopulardf = pd.DataFrame({"Item ID": [mostpopular2],
                              "Item Name": [mostpopular3],
                         
                             "Purchase Count": [mostpopular4],
                             "Item Price": [mostpopular5],
                             "Total Purchase Value": [mostpopular6]})
mostpopulardf

   Item ID  Item Name  Purchase Count  Item Price  Total Purchase Value
0      780        780             780     2379.77               2379.77

In [125]:
#most profitable items
mostprofitable1 = purchasedata.groupby(["SN"])
mostprofitable2 = purchasedata.count()["Item ID"]
mostprofitable3 = purchasedata.count()["Item Name"]
mostprofitable4 = purchasedata.count()["Price"]
mostprofitable5 = purchasedata.sum()["Price"]
mostprofitable6 = purchasedata.sum()["Price"]

In [126]:
mostprofitabledf = pd.Data.Frame({"Item ID": [mostprofitable2],
                              "Item Name": [mostprofitable3],
                             "Purchase Count": [mostprofitable4],
                             "Item Price": [mostprofitable5],
                             "Total Purchase Value": [mostprofitable6]})
mostprofitabledf

AttributeError: module 'pandas' has no attribute 'Data'