In [61]:
import pandas as pd
import numpy as np

In [62]:
file1 =("pandashomeworkfolder/purchase_data.csv")

In [63]:
purchasedata = pd.read_csv(file1)
purchasedata.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44

In [64]:
players = len(purchasedata)
numberofplayers = pd.DataFrame([players], columns = ["Total Players"])
numberofplayers

   Total Players
0            780

In [68]:
averagepurchaseprice = purchasedata["Price"].mean()
averagepurchaseprice

3.0509871794871795

In [69]:
numberofpurchases = len(purchasedata["Number Of Purchases"])
numberofpurchases

KeyError: 'Number Of Purchases'

In [67]:
uniqueitems = file1["UniqueItems"

KeyError: 'Unique'